

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class ExpenseItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the ExpenseItem entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ExpenseItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ExpenseItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ExpenseItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.ExpenseItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExpenseItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExpenseItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.ExpenseItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.ExpenseItem.DetailsClass.SetValue(this, global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.ExpenseItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.ExpenseItem.DetailsClass.SetValue(this, global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.ExpenseItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.ExpenseItem.DetailsClass.SetValue(this, global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal Amount
        {
            get
            {
                return global::LightSwitchApplication.ExpenseItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties.Amount);
            }
            set
            {
                global::LightSwitchApplication.ExpenseItem.DetailsClass.SetValue(this, global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties.Amount, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Amount_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Amount_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Amount_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DateIncurred
        {
            get
            {
                return global::LightSwitchApplication.ExpenseItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties.DateIncurred);
            }
            set
            {
                global::LightSwitchApplication.ExpenseItem.DetailsClass.SetValue(this, global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties.DateIncurred, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateIncurred_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateIncurred_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateIncurred_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.ExpenseReport ExpenseReport
        {
            get
            {
                return global::LightSwitchApplication.ExpenseItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties.ExpenseReport);
            }
            set
            {
                global::LightSwitchApplication.ExpenseItem.DetailsClass.SetValue(this, global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties.ExpenseReport, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExpenseReport_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExpenseReport_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExpenseReport_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.ExpenseItem,
                global::LightSwitchApplication.ExpenseItem.DetailsClass,
                global::LightSwitchApplication.ExpenseItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass>.Entry
                __ExpenseItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.ExpenseItem.DetailsClass.__ExpenseItem_CreateNew,
                    global::LightSwitchApplication.ExpenseItem.DetailsClass.__ExpenseItem_Created,
                    global::LightSwitchApplication.ExpenseItem.DetailsClass.__ExpenseItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.ExpenseItem __ExpenseItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ExpenseItem> es)
            {
                return new global::LightSwitchApplication.ExpenseItem(es);
            }
            private static void __ExpenseItem_Created(global::LightSwitchApplication.ExpenseItem e)
            {
                e.ExpenseItem_Created();
            }
            private static bool __ExpenseItem_AllowSaveWithErrors(global::LightSwitchApplication.ExpenseItem e)
            {
                bool result = false;
                e.ExpenseItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, decimal> Amount
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties.Amount) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, global::System.DateTime> DateIncurred
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties.DateIncurred) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, global::LightSwitchApplication.ExpenseReport> ExpenseReport
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties.ExpenseReport) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, global::LightSwitchApplication.ExpenseReport>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string Description { get; set; }
                new decimal Amount { get; set; }
                new global::System.DateTime DateIncurred { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation ExpenseReport { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ExpenseItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.ExpenseItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.ExpenseItem e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.ExpenseItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.ExpenseItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.ExpenseItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.ExpenseItem e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ExpenseItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.ExpenseItem.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.ExpenseItem e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.ExpenseItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.ExpenseItem.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.ExpenseItem.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.ExpenseItem e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ExpenseItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.ExpenseItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.ExpenseItem e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.ExpenseItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.ExpenseItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.ExpenseItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.ExpenseItem e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, decimal>.Entry
                    Amount = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, decimal>.Entry(
                        "Amount",
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._Amount_Stub,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._Amount_ComputeIsReadOnly,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._Amount_Validate,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._Amount_GetImplementationValue,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._Amount_SetImplementationValue,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._Amount_OnValueChanged);
                private static void _Amount_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ExpenseItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.ExpenseItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Amount, sf);
                }
                private static bool _Amount_ComputeIsReadOnly(global::LightSwitchApplication.ExpenseItem e)
                {
                    bool result = false;
                    e.Amount_IsReadOnly(ref result);
                    return result;
                }
                private static void _Amount_Validate(global::LightSwitchApplication.ExpenseItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Amount_Validate(r);
                }
                private static decimal _Amount_GetImplementationValue(global::LightSwitchApplication.ExpenseItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Amount;
                }
                private static void _Amount_SetImplementationValue(global::LightSwitchApplication.ExpenseItem.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.Amount = v;
                }
                private static void _Amount_OnValueChanged(global::LightSwitchApplication.ExpenseItem e)
                {
                    e.Amount_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, global::System.DateTime>.Entry
                    DateIncurred = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, global::System.DateTime>.Entry(
                        "DateIncurred",
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._DateIncurred_Stub,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._DateIncurred_ComputeIsReadOnly,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._DateIncurred_Validate,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._DateIncurred_GetImplementationValue,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._DateIncurred_SetImplementationValue,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._DateIncurred_OnValueChanged);
                private static void _DateIncurred_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ExpenseItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.ExpenseItem.DetailsClass d, object sf)
                {
                    c(d, ref d._DateIncurred, sf);
                }
                private static bool _DateIncurred_ComputeIsReadOnly(global::LightSwitchApplication.ExpenseItem e)
                {
                    bool result = false;
                    e.DateIncurred_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateIncurred_Validate(global::LightSwitchApplication.ExpenseItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateIncurred_Validate(r);
                }
                private static global::System.DateTime _DateIncurred_GetImplementationValue(global::LightSwitchApplication.ExpenseItem.DetailsClass d)
                {
                    return d.ImplementationEntity.DateIncurred;
                }
                private static void _DateIncurred_SetImplementationValue(global::LightSwitchApplication.ExpenseItem.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.DateIncurred = global::LightSwitchApplication.ExpenseItem.DetailsClass.TruncateDate(v);
                }
                private static void _DateIncurred_OnValueChanged(global::LightSwitchApplication.ExpenseItem e)
                {
                    e.DateIncurred_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, global::LightSwitchApplication.ExpenseReport>.Entry
                    ExpenseReport = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, global::LightSwitchApplication.ExpenseReport>.Entry(
                        "ExpenseReport",
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._ExpenseReport_Stub,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._ExpenseReport_ComputeIsReadOnly,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._ExpenseReport_Validate,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._ExpenseReport_GetCoreImplementationValue,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._ExpenseReport_GetImplementationValue,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._ExpenseReport_SetImplementationValue,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._ExpenseReport_Refresh,
                        global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties._ExpenseReport_OnValueChanged);
                private static void _ExpenseReport_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ExpenseItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, global::LightSwitchApplication.ExpenseReport>.Data> c, global::LightSwitchApplication.ExpenseItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ExpenseReport, sf);
                }
                private static bool _ExpenseReport_ComputeIsReadOnly(global::LightSwitchApplication.ExpenseItem e)
                {
                    bool result = false;
                    e.ExpenseReport_IsReadOnly(ref result);
                    return result;
                }
                private static void _ExpenseReport_Validate(global::LightSwitchApplication.ExpenseItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ExpenseReport_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _ExpenseReport_GetCoreImplementationValue(global::LightSwitchApplication.ExpenseItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ExpenseReport;
                }
                private static global::LightSwitchApplication.ExpenseReport _ExpenseReport_GetImplementationValue(global::LightSwitchApplication.ExpenseItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass>(global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties.ExpenseReport, ref d._ExpenseReport);
                }
                private static void _ExpenseReport_SetImplementationValue(global::LightSwitchApplication.ExpenseItem.DetailsClass d, global::LightSwitchApplication.ExpenseReport v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties.ExpenseReport, ref d._ExpenseReport, (i, ev) => i.ExpenseReport = ev, v);
                }
                private static void _ExpenseReport_Refresh(global::LightSwitchApplication.ExpenseItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.ExpenseItem.DetailsClass.PropertySetProperties.ExpenseReport, ref d._ExpenseReport);
                }
                private static void _ExpenseReport_OnValueChanged(global::LightSwitchApplication.ExpenseItem e)
                {
                    e.ExpenseReport_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, decimal>.Data _Amount;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, global::System.DateTime>.Data _DateIncurred;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass, global::LightSwitchApplication.ExpenseReport>.Data _ExpenseReport;
            
        }
    
        #endregion
    }
    
    #endregion
}
