

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class ExpenseReport : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the ExpenseReport entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ExpenseReport()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ExpenseReport(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ExpenseReport> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.ExpenseReport.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExpenseReport_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExpenseReport_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.ExpenseReport.DetailsClass.GetValue(this, global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.ExpenseReport.DetailsClass.SetValue(this, global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.ExpenseReport.DetailsClass.GetValue(this, global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.ExpenseReport.DetailsClass.SetValue(this, global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.ExpenseReport.DetailsClass.GetValue(this, global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.ExpenseReport.DetailsClass.SetValue(this, global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime CreationDate
        {
            get
            {
                return global::LightSwitchApplication.ExpenseReport.DetailsClass.GetValue(this, global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.CreationDate);
            }
            set
            {
                global::LightSwitchApplication.ExpenseReport.DetailsClass.SetValue(this, global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.CreationDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreationDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreationDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreationDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Status
        {
            get
            {
                return global::LightSwitchApplication.ExpenseReport.DetailsClass.GetValue(this, global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.Status);
            }
            set
            {
                global::LightSwitchApplication.ExpenseReport.DetailsClass.SetValue(this, global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.Status, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Status_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Status_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Status_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string UserName
        {
            get
            {
                return global::LightSwitchApplication.ExpenseReport.DetailsClass.GetValue(this, global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.UserName);
            }
            set
            {
                global::LightSwitchApplication.ExpenseReport.DetailsClass.SetValue(this, global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.UserName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.ExpenseItem> ExpenseItems
        {
            get
            {
                return global::LightSwitchApplication.ExpenseReport.DetailsClass.GetValue(this, global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.ExpenseItems);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.ExpenseItem> ExpenseItemsQuery
        {
            get
            {
                return global::LightSwitchApplication.ExpenseReport.DetailsClass.GetQuery(this, global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.ExpenseItems);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.ExpenseReport,
                global::LightSwitchApplication.ExpenseReport.DetailsClass,
                global::LightSwitchApplication.ExpenseReport.DetailsClass.IImplementation,
                global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass>.Entry
                __ExpenseReportEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass>.Entry(
                    global::LightSwitchApplication.ExpenseReport.DetailsClass.__ExpenseReport_CreateNew,
                    global::LightSwitchApplication.ExpenseReport.DetailsClass.__ExpenseReport_Created,
                    global::LightSwitchApplication.ExpenseReport.DetailsClass.__ExpenseReport_AllowSaveWithErrors);
            private static global::LightSwitchApplication.ExpenseReport __ExpenseReport_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ExpenseReport> es)
            {
                return new global::LightSwitchApplication.ExpenseReport(es);
            }
            private static void __ExpenseReport_Created(global::LightSwitchApplication.ExpenseReport e)
            {
                e.ExpenseReport_Created();
            }
            private static bool __ExpenseReport_AllowSaveWithErrors(global::LightSwitchApplication.ExpenseReport e)
            {
                bool result = false;
                e.ExpenseReport_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, global::System.DateTime> CreationDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.CreationDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, string> Status
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.Status) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, string> UserName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.UserName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, global::LightSwitchApplication.ExpenseItem> ExpenseItems
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.ExpenseItems) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, global::LightSwitchApplication.ExpenseItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string Description { get; set; }
                new global::System.DateTime CreationDate { get; set; }
                new string Status { get; set; }
                new string UserName { get; set; }
                new global::System.Collections.IEnumerable ExpenseItems { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ExpenseReport.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, int>.Data> c, global::LightSwitchApplication.ExpenseReport.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.ExpenseReport e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.ExpenseReport e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.ExpenseReport.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.ExpenseReport.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.ExpenseReport e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ExpenseReport.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.ExpenseReport.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.ExpenseReport e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.ExpenseReport e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.ExpenseReport.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.ExpenseReport.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.ExpenseReport e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ExpenseReport.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, string>.Data> c, global::LightSwitchApplication.ExpenseReport.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.ExpenseReport e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.ExpenseReport e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.ExpenseReport.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.ExpenseReport.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.ExpenseReport e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, global::System.DateTime>.Entry
                    CreationDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, global::System.DateTime>.Entry(
                        "CreationDate",
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._CreationDate_Stub,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._CreationDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._CreationDate_Validate,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._CreationDate_GetImplementationValue,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._CreationDate_SetImplementationValue,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._CreationDate_OnValueChanged);
                private static void _CreationDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ExpenseReport.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.ExpenseReport.DetailsClass d, object sf)
                {
                    c(d, ref d._CreationDate, sf);
                }
                private static bool _CreationDate_ComputeIsReadOnly(global::LightSwitchApplication.ExpenseReport e)
                {
                    bool result = false;
                    e.CreationDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreationDate_Validate(global::LightSwitchApplication.ExpenseReport e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreationDate_Validate(r);
                }
                private static global::System.DateTime _CreationDate_GetImplementationValue(global::LightSwitchApplication.ExpenseReport.DetailsClass d)
                {
                    return d.ImplementationEntity.CreationDate;
                }
                private static void _CreationDate_SetImplementationValue(global::LightSwitchApplication.ExpenseReport.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.CreationDate = global::LightSwitchApplication.ExpenseReport.DetailsClass.TruncateDate(v);
                }
                private static void _CreationDate_OnValueChanged(global::LightSwitchApplication.ExpenseReport e)
                {
                    e.CreationDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, string>.Entry
                    Status = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, string>.Entry(
                        "Status",
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._Status_Stub,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._Status_ComputeIsReadOnly,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._Status_Validate,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._Status_GetImplementationValue,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._Status_SetImplementationValue,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._Status_OnValueChanged);
                private static void _Status_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ExpenseReport.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, string>.Data> c, global::LightSwitchApplication.ExpenseReport.DetailsClass d, object sf)
                {
                    c(d, ref d._Status, sf);
                }
                private static bool _Status_ComputeIsReadOnly(global::LightSwitchApplication.ExpenseReport e)
                {
                    bool result = false;
                    e.Status_IsReadOnly(ref result);
                    return result;
                }
                private static void _Status_Validate(global::LightSwitchApplication.ExpenseReport e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Status_Validate(r);
                }
                private static string _Status_GetImplementationValue(global::LightSwitchApplication.ExpenseReport.DetailsClass d)
                {
                    return d.ImplementationEntity.Status;
                }
                private static void _Status_SetImplementationValue(global::LightSwitchApplication.ExpenseReport.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Status = v;
                }
                private static void _Status_OnValueChanged(global::LightSwitchApplication.ExpenseReport e)
                {
                    e.Status_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, string>.Entry
                    UserName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, string>.Entry(
                        "UserName",
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._UserName_Stub,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._UserName_ComputeIsReadOnly,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._UserName_Validate,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._UserName_GetImplementationValue,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._UserName_SetImplementationValue,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._UserName_OnValueChanged);
                private static void _UserName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ExpenseReport.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, string>.Data> c, global::LightSwitchApplication.ExpenseReport.DetailsClass d, object sf)
                {
                    c(d, ref d._UserName, sf);
                }
                private static bool _UserName_ComputeIsReadOnly(global::LightSwitchApplication.ExpenseReport e)
                {
                    bool result = false;
                    e.UserName_IsReadOnly(ref result);
                    return result;
                }
                private static void _UserName_Validate(global::LightSwitchApplication.ExpenseReport e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.UserName_Validate(r);
                }
                private static string _UserName_GetImplementationValue(global::LightSwitchApplication.ExpenseReport.DetailsClass d)
                {
                    return d.ImplementationEntity.UserName;
                }
                private static void _UserName_SetImplementationValue(global::LightSwitchApplication.ExpenseReport.DetailsClass d, string v)
                {
                    d.ImplementationEntity.UserName = v;
                }
                private static void _UserName_OnValueChanged(global::LightSwitchApplication.ExpenseReport e)
                {
                    e.UserName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, global::LightSwitchApplication.ExpenseItem>.Entry
                    ExpenseItems = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, global::LightSwitchApplication.ExpenseItem>.Entry(
                        "ExpenseItems",
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._ExpenseItems_Stub,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._ExpenseItems_GetReferencedEntities,
                        global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties._ExpenseItems_GetEntityCollection);
                private static void _ExpenseItems_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ExpenseReport.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, global::LightSwitchApplication.ExpenseItem>.Data> c, global::LightSwitchApplication.ExpenseReport.DetailsClass d, object sf)
                {
                    c(d, ref d._ExpenseItems, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.ExpenseItem> _ExpenseItems_GetReferencedEntities(global::LightSwitchApplication.ExpenseReport.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.ExpenseItem, global::LightSwitchApplication.ExpenseItem.DetailsClass>(global::LightSwitchApplication.ExpenseReport.DetailsClass.PropertySetProperties.ExpenseItems, ref d._ExpenseItems);
                }
                private static global::System.Collections.IEnumerable _ExpenseItems_GetEntityCollection(global::LightSwitchApplication.ExpenseReport.DetailsClass d)
                {
                    return d.ImplementationEntity.ExpenseItems;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, global::System.DateTime>.Data _CreationDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, string>.Data _Status;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, string>.Data _UserName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ExpenseReport, global::LightSwitchApplication.ExpenseReport.DetailsClass, global::LightSwitchApplication.ExpenseItem>.Data _ExpenseItems;
            
        }
    
        #endregion
    }
    
    #endregion
}
